#+TITLE: Lemonad
#+AUTHOR: Fogus

#+INCLUDE: menu.org org

* a functional JavaScript library

Lemonad is a JavaScript library supporting functional programming inspired by [[http://clojure.org][Clojure]], [[http://github.com/clojure/clojurescript][ClojureScript]], [[http://osteele.com/sources/javascript/functional/][Functional JavaScript]], ML, Haskell, Forth and [[http://underscorejs.org/][Underscore]].

* why?

I thought this might be useful for others, so here it is.  Enjoy.

* getting

Lemonad can be installed via [[http://npmjs.org/package/lemonad][NPM]] by adding the following to your ~package.json~ file:

#+begin_src javascript
"dependencies": {
  "lemonad": ">= 0.7.4",
}
#+end_src

You can also find the Lemonad source code on Github at  https://github.com/fogus/lemonad.

* including

Whether you use Lemonad via [[http://nodejs.org][Node.js]], within a web page or some other method, including the ~lemonad.js~ file defines a global variable named ~L~ that is used as the module for its capabilities.

On a web page, you'll need to do the following:

#+begin_src html
<script type="text/javascript" src="lemonad.js"></script>
#+end_src

* using

Documentation for using Lemonad is in development.  For now you can look at the [[http://fogus.github.com/lemonad/test.html][Lemonad specs]] and [[https://github.com/fogus/lemonad/tree/master/test][their source code]] to get a feel for using it.

* thanks

Remember, [[https://github.com/fogus/lemonad/issues][contributions welcomed]].


#+STYLE: <link rel="stylesheet" type="text/css" href="common.css" />
#+STYLE: <link rel="stylesheet" type="text/css" href="screen.css" />
#+OPTIONS: toc:nil

# Local Variables:
# org-export-html-style-include-default: nil
# org-export-html-style-include-scripts: nil
# buffer-file-coding-system: utf-8-unix
# End:
